// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  apiKey: "AIzaSyCqbjqRj0Y9i8uScTpxdaODLRmIXXDjcg4",
  authDomain: "deliberate-383ce.firebaseapp.com",
  projectId: "deliberate-383ce",
  storageBucket: "deliberate-383ce.appspot.com",
  messagingSenderId: "451904815993",
  appId: "1:451904815993:web:af01fc4229fe8a708a65a8",
  measurementId: "G-TKFGDHRPP3"
};
